import {
  FilterOutlined,
  SearchOutlined,
  CommentOutlined,
  HeartOutlined,
  CloseOutlined,
  LeftOutlined,
  MenuOutlined,
  UserOutlined,
  StarFilled,
  CheckCircleFilled,
  CaretUpOutlined,
  UpOutlined,
  AlignLeftOutlined,
  SettingOutlined,
  CheckCircleOutlined,
  DeleteOutlined,
  WalletOutlined,
  DownOutlined,
  PlusCircleOutlined,
} from '@ant-design/icons'

const Iconmap: { [unit: string]: object } = {
  PlusCircleOutlined: <PlusCircleOutlined />,
  FilterOutlined: <FilterOutlined />,
  SettingOutlined: <SettingOutlined />,
  CheckCircleOutlined: <CheckCircleOutlined />,
  DeleteOutlined: <DeleteOutlined />,
  DownOutlined: <DownOutlined />,
  SearchOutlined: <SearchOutlined />,
  WalletOutlined: <WalletOutlined />,
  CommentOutlined: <CommentOutlined />,
  HeartOutlined: <HeartOutlined />,
  CloseOutlined: <CloseOutlined />,
  LeftOutlined: <LeftOutlined />,
  MenuOutlined: <MenuOutlined />,
  UserOutlined: <UserOutlined />,
  StarFilled: <StarFilled />,
  CheckCircleFilled: <CheckCircleFilled />,
  CaretUpOutlined: <CaretUpOutlined />,
  UpOutlined: <UpOutlined />,
  AlignLeftOutlined: <AlignLeftOutlined />,
}

export default Iconmap
